### ISSUE TITLE
Error: ChatGPT failed to refresh auth token. Error: 403 Forbidden

### ISSUE THREAD

**Issue by Licyldj** [realies/chatgpt-telegram-bot#3]
at ChatGPTAPI.refreshAccessToken (file:///app/node_modules/chatgpt/build/index.js:259:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ChatGPTAPI.ensureAuth (file:///app/node_modules/chatgpt/build/index.js:225:12)
    at async file:///app/server.js:7:3

**Comment by realies** [comment]
@Licyldj, a few days ago, OpenAI added Cloudflare on top of their service, which occasionally requires captchas to be filled in. This can't be automated currently and probably won't be feasible within a Docker container if not automated. It could potentially have a headful browser, but I'm not sure that could be containerised and made cross-platform easily.
